# Generated by Django 2.2 on 2019-04-09 18:04


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datame', '0001_initial'),

    ]

    operations = [
        migrations.CreateModel(
            name='OfferPaypalBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=64)),
                ('payer_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('pagado', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('offer', models.OneToOneField(on_delete=models.SET(0), to='datame.Offer')),
            ],
        ),
    ]
