# Generated by Django 2.1 on 2019-04-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20190411_0800'),
        ('pagos', '0002_auto_20190410_1917'),
        ('pagos', '0002_userplanpaypalbill'),
    ]

    operations = [
    ]
