# Generated by Django 2.2 on 2019-04-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_merge_20190411_1611'),
        ('pagos', '0003_merge_20190411_2237'),
    ]

    operations = [
    ]
