# Generated by Django 2.1 on 2019-04-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='DataScientist',
            new_name='dataScientist',
        ),
    ]
