# Generated by Django 2.1 on 2019-04-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_start',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
