# Generated by Django 2.1 on 2019-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0002_auto_20190402_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='expirationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
