# Generated by Django 2.1 on 2019-04-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0003_auto_20190402_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='dataScientist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datame.DataScientist'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='expirationDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='type',
            field=models.CharField(choices=[('PRO', 'PRO')], max_length=4, verbose_name='Type'),
        ),
    ]
