# Generated by Django 2.1.7 on 2019-04-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0003_auto_20190402_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isAlert',
            field=models.BooleanField(default=False),
        ),
    ]
