# Generated by Django 2.1 on 2019-04-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0004_message_isalert'),
        ('datame', '0004_auto_20190405_2013'),
    ]

    operations = [
    ]
